[package]
name = "forte_core"
version = "0.1.0"
authors = ["Mcat12 <newtoncat12@yahoo.com>", "0xcaff <martincharles07@gmail.com>"]

[profile.release]
lto = true

[[bin]]
name = "forte"
path = "src/bin/main.rs"

[dependencies]
r2d2 = "0.8.0"
r2d2-diesel = "1.0.0"
diesel_migrations = "1.3.0"
diesel = { version = "1.0.0", features = ["sqlite", "chrono"] }
chrono = "0.4"
uuid = { version = "0.6.3", features = ["v4", "serde"] }
actix = "0.5.7"
actix-web = "0.6.10"
ffmpeg = { git = "https://github.com/forte-music/rust-ffmpeg.git", branch = "master", features = ["build"] }
bytes = "0.4.7"
futures-cpupool = "0.1.8"
serde = "1.0.62"
serde_json = "1.0.18"
serde_derive = "1.0.62"
juniper = "0.9.2"
mime_guess = "1.8.4"
taglib2-sys = { path = "taglib2-sys" }
image = "0.19.0"
walkdir = "2.1.4"
indicatif = { git = "https://github.com/mitsuhiko/indicatif.git", rev = "950091d1b1683a88e01c4d4975f591009f56322b" }
structopt = "0.2.8"
app_dirs = "1.2.1"
futures = "0.1.21"
error-chain = "0.11.0"
