[package]
name = "forte_core"
version = "0.1.0"
authors = ["Mcat12 <newtoncat12@yahoo.com>", "0xcaff <martincharles07@gmail.com>"]

[dependencies]
rocket = "0.3.6"
rocket_codegen = "0.3.6"
juniper = "0.9.2"
juniper_rocket = "0.1.2"
redis = "0.8.0"
r2d2 = "0.8.0"
r2d2_redis = "0.7.0"
serde = "1.0"
serde_derive = "1.0"
serde-redis = { git = "https://github.com/Mcat12/serde-redis.git", branch = "fix/bool-decode" }
time = "0.1"
