[package]
name = "forte-core"
version = "0.1.0"
authors = ["Mcat12 <newtoncat12@yahoo.com>", "0xcaff <martincharles07@gmail.com>"]

[dependencies]
rocket = "0.3.4"
rocket_codegen = "0.3.4"
juniper = "0.9.1"
juniper_rocket = "0.1.1"
redis = "0.8.0"
r2d2 = "0.8.0"
r2d2_redis = "0.7.0"
