[package]
name = "forte_core"
version = "0.1.0"
authors = ["Mcat12 <newtoncat12@yahoo.com>", "0xcaff <martincharles07@gmail.com>"]

[profile.release]
lto = true

[[bin]]
name = "forte"
path = "src/bin/main.rs"

[dependencies]
diesel = { version = "1.0.0", features = ["sqlite", "chrono"] }
chrono = "0.4"
uuid = { version = "0.6.3", features = ["v4"] }
juniper = "0.9.2"
juniper_iron = "0.1.2"
r2d2 = "0.8.0"
r2d2-diesel = "1.0.0"
taglib2-sys = { path = "taglib2-sys" }
error-chain = "0.11.0"
walkdir = "2.1.4"
indicatif = "0.9.0"
router = "0.6.0"
iron = "0.6.0"
logger = "0.4.0"
persistent = "0.4.0"
structopt = "0.2.8"
app_dirs = "1.2.1"
diesel_migrations = "1.3.0"
mime_guess = "1.8.4"
image = "0.19.0"
