version: 2

aliases:
  - &restore_cargo_cache
    keys:
      - v2-cargo-{{ checksum "Cargo.lock" }}
      - cargo-

  - &restore_fixture_cache
    keys:
      - fixture-{{ checksum "fixture_setup/Cargo.lock" }}
      - fixture-

  - &restore_yarn_cache
    keys:
      - yarn-{{ checksum "fixture_setup/yarn.lock" }}
      - yarn-

  - &save_cargo_cache
    key: v2-cargo-{{ checksum "Cargo.lock" }}
    paths:
      - target
      - ~/.cargo

  - &save_fixture_cache
    key: fixture-{{ checksum "fixture_setup/Cargo.lock" }}
    paths:
      - fixture_setup/target

  - &save_yarn_cache
    key: yarn-{{ checksum "fixture_setup/yarn.lock" }}
    paths:
      - fixture_setup/node_modules

jobs:
  lint:
    docker:
      - image: fortemusic/core-build

    steps:
      - checkout

      - run:
          name: Checkout Git Submodules
          command: git submodule update --init

      - restore_cache: *restore_cargo_cache

      - run:
          name: Check for Errors
          command: |
            cargo clean
            cargo check
            cd fixture_setup
            cargo check

      - save_cache: *save_cargo_cache

      - run:
          name: Check Formatting
          command: |
            cargo fmt -- --write-mode=diff
            cd fixture_setup
            cargo fmt -- --write-mode=diff

      - run:
          name: Check Linting
          command: |
            cargo clippy -- -D warnings
            cd fixture_setup
            cargo clippy -- -D warnings

      - save_cache: *save_cargo_cache

  test:
    docker:
      # Primary container
      - image: fortemusic/core-build

      # Secondary container (available on localhost)
      - image: redis:4.0.6

    steps:
      - checkout

      - run:
          name: Checkout Git Submodules
          command: git submodule update --init

      - restore_cache: *restore_cargo_cache

      - restore_cache: *restore_fixture_cache

      - restore_cache: *restore_yarn_cache

      - run:
          name: Install Schema
          working_directory: fixture_setup
          command: yarn install

      - run:
          name: Install Fixtures
          working_directory: fixture_setup
          command: cargo run

      - save_cache: *save_fixture_cache

      - save_cache: *save_yarn_cache

      - run:
          name: Build Core
          command: cargo build

      - run:
          name: Start Core
          environment:
            - ROCKET_ADDRESS: 127.0.0.1
          background: true
          command: cargo run

      - run:
          name: Run Tests
          working_directory: fixture_setup
          command: |
            wait-for localhost:8000 -- echo "Core started"
            yarn run forte-test-api http://localhost:8000/graphql

workflows:
  version: 2
  test:
    jobs:
      - lint
      - test
