version: 2

aliases:
  - &restore_cache
    keys:
      - cargo-{{ checksum "Cargo.toml" }}-{{ checksum "fixture_setup/Cargo.toml" }}-{{ checksum "fixture_setup/package.json" }}
      - cargo-{{ checksum "Cargo.toml" }}-{{ checksum "fixture_setup/Cargo.toml" }}
      - cargo-{{ checksum "Cargo.toml" }}
      - cargo-

  - &save_cache
    key: cargo-{{ checksum "Cargo.toml" }}
    paths:
      - target
      - ~/.cargo
      - fixture_setup/target
      - fixture_setup/node_modules

jobs:
  lint:
    docker:
      - image: fortemusic/core-build

    steps:
      - checkout

      - restore_cache: *restore_cache

      - run:
          name: Check for Errors
          command: |
            cargo check
            cd fixture_setup
            cargo check

      - save_cache: *save_cache

      - run:
          name: Check Formatting
          command: |
            cargo fmt -- --write-mode=diff
            cd fixture_setup
            cargo fmt -- --write-mode=diff

      - run:
          name: Check Linting
          command: |
            cargo clippy -- -D warnings
            cd fixture_setup
            cargo clippy -- -D warnings

      - save_cache: *save_cache

  test:
    docker:
      # Primary container
      - image: fortemusic/core-build

      # Secondary container (available on localhost)
      - image: redis:4.0.6

    steps:
      - checkout

      - restore_cache: *restore_cache

      - run:
          name: Install Schema
          command: |
            cd fixture_setup
            yarn install

      - run:
          name: Install Fixtures
          command: |
            cd fixture_setup
            cargo run

      - run:
          name: Build Core
          command: cargo build

      - run:
          name: Start Core
          environment:
            - ROCKET_ADDRESS: 127.0.0.1
          background: true
          # Start core as a daemon logging to server.log
          command: cargo run

      - run:
          name: Run Tests
          command: |
            cd fixture_setup
            #wait-for localhost:8000 -- echo "Core started"
            yarn run forte-test-api http://localhost:8000/graphql

      # Don't save the cache (use the cache generated by lint)

workflows:
  version: 2
  test:
    jobs:
      - lint
      - test
