version: 2

aliases:
  - &restore_cache
    keys:
      - cargo-{{ checksum "Cargo.toml" }}
      - cargo-

  - &save_cache
    key: cargo-{{ checksum "Cargo.toml" }}
    paths:
      - target
      - ~/.cargo

jobs:
  lint:
    docker:
      - image: 0xcaff/rust-nightly

    steps:
      - checkout

      - restore_cache: *restore_cache

      - run:
          name: Install Dependencies and Build
          command: cargo build

      - save_cache: *save_cache

      - run:
          name: Check Formatting
          command: cargo fmt -- --write-mode=diff

      - run:
          name: Lint
          command: cargo clippy -- -D warnings

  test:
    docker:
      # Primary container
      - image: 0xcaff/rust-nightly

      # Secondary container (available on localhost)
      - image: redis:4.0.6

    steps:
      - checkout

      - restore_cache: *restore_cache

      - run:
          name: Install Fixtures
          command: |
            cd fixture_setup
            cargo run

      - run:
          name: Start Core
          # Start core as a daemon logging to server.log
          command: cargo run >server.log 2>&1 &

      # TODO: Run tests

      # Don't save the cache (use the cache generated by lint)

workflows:
  version: 2
  test:
    jobs:
      - lint
      - test
