[package]
name = "fixture_setup"
version = "0.1.0"
authors = ["Mcat12 <newtoncat12@yahoo.com>", "0xcaff <martincharles07@gmail.com>"]

[dependencies]
forte_core = { path = ".." }
serde_derive = "1.0"
serde = "1.0"
toml = "0.4"
